// Include file for TreeMaker V12
//
// Declare leaf variables and provide a function to set the branch addresses
//  (Generated via TChain::MakeCode())

//Declaration of leaves types
  UInt_t          RunNum;
  UInt_t          LumiBlockNum;
  ULong64_t       EvtNum;
  Bool_t          BadChargedCandidateFilter;
  Bool_t          BadGlobalMuon;
  Double_t        BadGlobalMuonLeadPt;
  Bool_t          BadPFMuonFilter;
  Bool_t          BadTrkGlobalMuon;
  Double_t        BadTrkGlobalMuonLeadPt;
  Int_t           BTags;
  Int_t           BTagsMVA;
  Double_t        CaloMET;
  Double_t        CaloMETPhi;
  Double_t        CrossSection;
  Int_t           CSCTightHaloFilter;
  Double_t        DeltaPhi1;
  Double_t        DeltaPhi2;
  Double_t        DeltaPhi3;
  Double_t        DeltaPhi4;
  Bool_t          DupGlobalMuon;
  Double_t        DupGlobalMuonLeadPt;
  Int_t           EcalDeadCellTriggerPrimitiveFilter;
  Int_t           eeBadScFilter;
  vector<TLorentzVector> Electrons;
  vector<int>     Electrons_charge;
  vector<bool>    Electrons_mediumID;
  vector<double>  Electrons_MT2Activity;
  vector<double>  Electrons_MTW;
  vector<double>  Electrons_PTW;
  vector<bool>    Electrons_tightID;
  vector<TLorentzVector> ElectronsNoIso;
  vector<bool>    ElectronsNoIso_mediumID;
  vector<double>  ElectronsNoIso_MiniIso;
  vector<double>  ElectronsNoIso_MT2Activity;
  vector<double>  ElectronsNoIso_MTW;
  vector<bool>    ElectronsNoIso_tightID;
  vector<TLorentzVector> GenElectrons;
  vector<bool>    GenElectrons_fromTau;
  vector<double>  GenElectrons_MT2Activity;
  vector<double>  GenElectrons_RecoTrkAct;
  vector<double>  GenElectrons_RecoTrkd3;
  vector<double>  GenElectrons_RecoTrkIso;
  Double_t        GenHT;
  vector<TLorentzVector> GenJets;
  vector<bool>    GenJets_HTMask;
  vector<bool>    GenJets_MHTMask;
  Double_t        GenMET;
  Double_t        GenMETPhi;
  Double_t        GenMHT;
  Double_t        GenMHTPhi;
  vector<TLorentzVector> GenMuons;
  vector<bool>    GenMuons_fromTau;
  vector<double>  GenMuons_MT2Activity;
  vector<double>  GenMuons_RecoTrkAct;
  vector<double>  GenMuons_RecoTrkd3;
  vector<double>  GenMuons_RecoTrkIso;
  vector<TLorentzVector> GenParticles;
  vector<int>     GenParticles_ParentId;
  vector<int>     GenParticles_ParentIdx;
  vector<int>     GenParticles_PdgId;
  vector<int>     GenParticles_Status;
  vector<TLorentzVector> GenTaus;
  vector<bool>    GenTaus_had;
  vector<double>  GenTaus_LeadRecoTrkAct;
  vector<double>  GenTaus_LeadRecoTrkd3;
  vector<double>  GenTaus_LeadRecoTrkIso;
  vector<TLorentzVector> GenTaus_LeadTrk;
  vector<double>  GenTaus_MT2Activity;
  vector<int>     GenTaus_NNeutralHadrons;
  vector<int>     GenTaus_NProngs;
  vector<TLorentzVector> GenTaus_Nu;
  vector<TLorentzVector> GenTops;
  Double_t        GenTopWeight;
  Int_t           globalTightHalo2016Filter;
  Bool_t          hasGenPromptPhoton;
  Int_t           HBHEIsoNoiseFilter;
  Int_t           HBHENoiseFilter;
  Double_t        HT;
  Int_t           isoElectronTracks;
  Int_t           isoMuonTracks;
  Int_t           isoPionTracks;
  Bool_t          JetID;
  Bool_t          JetIDAK8;
  vector<TLorentzVector> Jets;
  vector<double>  Jets_bDiscriminatorCSV;
  vector<double>  Jets_bDiscriminatorMVA;
  vector<double>  Jets_chargedEmEnergyFraction;
  vector<double>  Jets_chargedHadronEnergyFraction;
  vector<int>     Jets_chargedHadronMultiplicity;
  vector<int>     Jets_chargedMultiplicity;
  vector<int>     Jets_electronMultiplicity;
  vector<int>     Jets_hadronFlavor;
  vector<bool>    Jets_HTMask;
  vector<bool>    Jets_ID;
  vector<bool>    Jets_ISRMask;
  vector<double>  Jets_jecFactor;
  vector<double>  Jets_jecUnc;
  vector<double>  Jets_jerFactor;
  vector<double>  Jets_jerFactorDown;
  vector<double>  Jets_jerFactorUp;
  vector<bool>    Jets_LeptonMask;
  vector<bool>    Jets_MHTMask;
  vector<double>  Jets_muonEnergyFraction;
  vector<int>     Jets_muonMultiplicity;
  vector<double>  Jets_neutralEmEnergyFraction;
  vector<double>  Jets_neutralHadronEnergyFraction;
  vector<int>     Jets_neutralHadronMultiplicity;
  vector<int>     Jets_neutralMultiplicity;
  vector<int>     Jets_partonFlavor;
  vector<double>  Jets_photonEnergyFraction;
  vector<int>     Jets_photonMultiplicity;
  vector<double>  Jets_qgAxis2;
  vector<double>  Jets_qgLikelihood;
  vector<int>     Jets_qgMult;
  vector<double>  Jets_qgPtD;
  vector<TLorentzVector> JetsAK8;
  vector<double>  JetsAK8_bDiscriminatorSubjet1CSV;
  vector<double>  JetsAK8_bDiscriminatorSubjet2CSV;
  vector<double>  JetsAK8_doubleBDiscriminator;
  vector<bool>    JetsAK8_ID;
  vector<double>  JetsAK8_NsubjettinessTau1;
  vector<double>  JetsAK8_NsubjettinessTau2;
  vector<double>  JetsAK8_NsubjettinessTau3;
  vector<int>     JetsAK8_NumBhadrons;
  vector<int>     JetsAK8_NumChadrons;
  vector<double>  JetsAK8_prunedMass;
  Double_t        madHT;
  Int_t           madMinDeltaRStatus;
  Double_t        madMinPhotonDeltaR;
  Double_t        MET;
  vector<double>  METDown;
  Double_t        METPhi;
  vector<double>  METPhiDown;
  vector<double>  METPhiUp;
  vector<double>  METUp;
  Double_t        MHT;
  Double_t        MHTPhi;
  Double_t        MT2;
  vector<TLorentzVector> Muons;
  vector<int>     Muons_charge;
  vector<double>  Muons_MT2Activity;
  vector<double>  Muons_MTW;
  vector<double>  Muons_PTW;
  vector<bool>    Muons_tightID;
  vector<TLorentzVector> MuonsNoIso;
  vector<double>  MuonsNoIso_MiniIso;
  vector<double>  MuonsNoIso_MT2Activity;
  vector<double>  MuonsNoIso_MTW;
  vector<bool>    MuonsNoIso_tightID;
  Int_t           nAllVertices;
  Int_t           NJets;
  Int_t           NJetsISR;
  Double_t        NumEvents;
  Int_t           NumInteractions;
  Int_t           NVtx;
  vector<int>     PDFids;
  vector<double>  PDFweights;
  Double_t        PFCaloMETRatio;
  vector<TLorentzVector> Photons;
  vector<bool>    Photons_electronFakes;
  vector<bool>    Photons_fullID;
  vector<double>  Photons_genMatched;
  vector<double>  Photons_hadTowOverEM;
  vector<double>  Photons_hasPixelSeed;
  vector<double>  Photons_isEB;
  vector<bool>    Photons_nonPrompt;
  vector<double>  Photons_passElectronVeto;
  vector<double>  Photons_pfChargedIso;
  vector<double>  Photons_pfChargedIsoRhoCorr;
  vector<double>  Photons_pfGammaIso;
  vector<double>  Photons_pfGammaIsoRhoCorr;
  vector<double>  Photons_pfNeutralIso;
  vector<double>  Photons_pfNeutralIsoRhoCorr;
  vector<double>  Photons_sigmaIetaIeta;
  Double_t        PmssmId;
  Double_t        puSysDown;
  Double_t        puSysUp;
  Double_t        puWeight;
  vector<double>  ScaleWeights;
  vector<TLorentzVector> SoftJets;
  vector<double>  SoftJets_bDiscriminatorCSV;
  vector<bool>    SoftJets_ID;
  vector<double>  SoftJets_jecFactor;
  vector<double>  SoftJets_jecUnc;
  vector<double>  SoftJets_jerFactor;
  vector<double>  SoftJets_jerFactorDown;
  vector<double>  SoftJets_jerFactorUp;
  Double_t        SusyLSPMass;
  Double_t        SusyMotherMass;
  vector<TLorentzVector> TAPElectronTracks;
  vector<double>  TAPElectronTracks_activity;
  vector<int>     TAPElectronTracks_charge;
  vector<double>  TAPElectronTracks_mT;
  vector<double>  TAPElectronTracks_trkiso;
  vector<TLorentzVector> TAPMuonTracks;
  vector<double>  TAPMuonTracks_activity;
  vector<int>     TAPMuonTracks_charge;
  vector<double>  TAPMuonTracks_mT;
  vector<double>  TAPMuonTracks_trkiso;
  vector<TLorentzVector> TAPPionTracks;
  vector<double>  TAPPionTracks_activity;
  vector<int>     TAPPionTracks_charge;
  vector<double>  TAPPionTracks_mT;
  vector<double>  TAPPionTracks_trkiso;
  vector<string>  TriggerNames;
  vector<int>     TriggerPass;
  vector<int>     TriggerPrescales;
  Double_t        TrueNumInteractions;
  Double_t        Weight;
  vector<TLorentzVector> ZCandidates;
  Double_t        HT5;
  UInt_t          RA2binBranch;
  vector<unsigned int> RA2bins;

  void setBranchAddress(TChain* chain) {

  // Set branch addresses.
  chain->SetBranchAddress("RunNum",&RunNum);
  chain->SetBranchAddress("LumiBlockNum",&LumiBlockNum);
  chain->SetBranchAddress("EvtNum",&EvtNum);
  chain->SetBranchAddress("BadChargedCandidateFilter",&BadChargedCandidateFilter);
  chain->SetBranchAddress("BadGlobalMuon",&BadGlobalMuon);
  chain->SetBranchAddress("BadGlobalMuonLeadPt",&BadGlobalMuonLeadPt);
  chain->SetBranchAddress("BadPFMuonFilter",&BadPFMuonFilter);
  chain->SetBranchAddress("BadTrkGlobalMuon",&BadTrkGlobalMuon);
  chain->SetBranchAddress("BadTrkGlobalMuonLeadPt",&BadTrkGlobalMuonLeadPt);
  chain->SetBranchAddress("BTags",&BTags);
  chain->SetBranchAddress("BTagsMVA",&BTagsMVA);
  chain->SetBranchAddress("CaloMET",&CaloMET);
  chain->SetBranchAddress("CaloMETPhi",&CaloMETPhi);
  chain->SetBranchAddress("CrossSection",&CrossSection);
  chain->SetBranchAddress("CSCTightHaloFilter",&CSCTightHaloFilter);
  chain->SetBranchAddress("DeltaPhi1",&DeltaPhi1);
  chain->SetBranchAddress("DeltaPhi2",&DeltaPhi2);
  chain->SetBranchAddress("DeltaPhi3",&DeltaPhi3);
  chain->SetBranchAddress("DeltaPhi4",&DeltaPhi4);
  chain->SetBranchAddress("DupGlobalMuon",&DupGlobalMuon);
  chain->SetBranchAddress("DupGlobalMuonLeadPt",&DupGlobalMuonLeadPt);
  chain->SetBranchAddress("EcalDeadCellTriggerPrimitiveFilter",&EcalDeadCellTriggerPrimitiveFilter);
  chain->SetBranchAddress("eeBadScFilter",&eeBadScFilter);
  chain->SetBranchAddress("Electrons",&Electrons);
  chain->SetBranchAddress("Electrons_charge",&Electrons_charge);
  chain->SetBranchAddress("Electrons_mediumID",&Electrons_mediumID);
  chain->SetBranchAddress("Electrons_MT2Activity",&Electrons_MT2Activity);
  chain->SetBranchAddress("Electrons_MTW",&Electrons_MTW);
  chain->SetBranchAddress("Electrons_PTW",&Electrons_PTW);
  chain->SetBranchAddress("Electrons_tightID",&Electrons_tightID);
  chain->SetBranchAddress("ElectronsNoIso",&ElectronsNoIso);
  chain->SetBranchAddress("ElectronsNoIso_mediumID",&ElectronsNoIso_mediumID);
  chain->SetBranchAddress("ElectronsNoIso_MiniIso",&ElectronsNoIso_MiniIso);
  chain->SetBranchAddress("ElectronsNoIso_MT2Activity",&ElectronsNoIso_MT2Activity);
  chain->SetBranchAddress("ElectronsNoIso_MTW",&ElectronsNoIso_MTW);
  chain->SetBranchAddress("ElectronsNoIso_tightID",&ElectronsNoIso_tightID);
  chain->SetBranchAddress("GenElectrons",&GenElectrons);
  chain->SetBranchAddress("GenElectrons_fromTau",&GenElectrons_fromTau);
  chain->SetBranchAddress("GenElectrons_MT2Activity",&GenElectrons_MT2Activity);
  chain->SetBranchAddress("GenElectrons_RecoTrkAct",&GenElectrons_RecoTrkAct);
  chain->SetBranchAddress("GenElectrons_RecoTrkd3",&GenElectrons_RecoTrkd3);
  chain->SetBranchAddress("GenElectrons_RecoTrkIso",&GenElectrons_RecoTrkIso);
  chain->SetBranchAddress("GenHT",&GenHT);
  chain->SetBranchAddress("GenJets",&GenJets);
  chain->SetBranchAddress("GenJets_HTMask",&GenJets_HTMask);
  chain->SetBranchAddress("GenJets_MHTMask",&GenJets_MHTMask);
  chain->SetBranchAddress("GenMET",&GenMET);
  chain->SetBranchAddress("GenMETPhi",&GenMETPhi);
  chain->SetBranchAddress("GenMHT",&GenMHT);
  chain->SetBranchAddress("GenMHTPhi",&GenMHTPhi);
  chain->SetBranchAddress("GenMuons",&GenMuons);
  chain->SetBranchAddress("GenMuons_fromTau",&GenMuons_fromTau);
  chain->SetBranchAddress("GenMuons_MT2Activity",&GenMuons_MT2Activity);
  chain->SetBranchAddress("GenMuons_RecoTrkAct",&GenMuons_RecoTrkAct);
  chain->SetBranchAddress("GenMuons_RecoTrkd3",&GenMuons_RecoTrkd3);
  chain->SetBranchAddress("GenMuons_RecoTrkIso",&GenMuons_RecoTrkIso);
  chain->SetBranchAddress("GenParticles",&GenParticles);
  chain->SetBranchAddress("GenParticles_ParentId",&GenParticles_ParentId);
  chain->SetBranchAddress("GenParticles_ParentIdx",&GenParticles_ParentIdx);
  chain->SetBranchAddress("GenParticles_PdgId",&GenParticles_PdgId);
  chain->SetBranchAddress("GenParticles_Status",&GenParticles_Status);
  chain->SetBranchAddress("GenTaus",&GenTaus);
  chain->SetBranchAddress("GenTaus_had",&GenTaus_had);
  chain->SetBranchAddress("GenTaus_LeadRecoTrkAct",&GenTaus_LeadRecoTrkAct);
  chain->SetBranchAddress("GenTaus_LeadRecoTrkd3",&GenTaus_LeadRecoTrkd3);
  chain->SetBranchAddress("GenTaus_LeadRecoTrkIso",&GenTaus_LeadRecoTrkIso);
  chain->SetBranchAddress("GenTaus_LeadTrk",&GenTaus_LeadTrk);
  chain->SetBranchAddress("GenTaus_MT2Activity",&GenTaus_MT2Activity);
  chain->SetBranchAddress("GenTaus_NNeutralHadrons",&GenTaus_NNeutralHadrons);
  chain->SetBranchAddress("GenTaus_NProngs",&GenTaus_NProngs);
  chain->SetBranchAddress("GenTaus_Nu",&GenTaus_Nu);
  chain->SetBranchAddress("GenTops",&GenTops);
  chain->SetBranchAddress("GenTopWeight",&GenTopWeight);
  chain->SetBranchAddress("globalTightHalo2016Filter",&globalTightHalo2016Filter);
  chain->SetBranchAddress("hasGenPromptPhoton",&hasGenPromptPhoton);
  chain->SetBranchAddress("HBHEIsoNoiseFilter",&HBHEIsoNoiseFilter);
  chain->SetBranchAddress("HBHENoiseFilter",&HBHENoiseFilter);
  chain->SetBranchAddress("HT",&HT);
  chain->SetBranchAddress("isoElectronTracks",&isoElectronTracks);
  chain->SetBranchAddress("isoMuonTracks",&isoMuonTracks);
  chain->SetBranchAddress("isoPionTracks",&isoPionTracks);
  chain->SetBranchAddress("JetID",&JetID);
  chain->SetBranchAddress("JetIDAK8",&JetIDAK8);
  chain->SetBranchAddress("Jets",&Jets);
  chain->SetBranchAddress("Jets_bDiscriminatorCSV",&Jets_bDiscriminatorCSV);
  chain->SetBranchAddress("Jets_bDiscriminatorMVA",&Jets_bDiscriminatorMVA);
  chain->SetBranchAddress("Jets_chargedEmEnergyFraction",&Jets_chargedEmEnergyFraction);
  chain->SetBranchAddress("Jets_chargedHadronEnergyFraction",&Jets_chargedHadronEnergyFraction);
  chain->SetBranchAddress("Jets_chargedHadronMultiplicity",&Jets_chargedHadronMultiplicity);
  chain->SetBranchAddress("Jets_chargedMultiplicity",&Jets_chargedMultiplicity);
  chain->SetBranchAddress("Jets_electronMultiplicity",&Jets_electronMultiplicity);
  chain->SetBranchAddress("Jets_hadronFlavor",&Jets_hadronFlavor);
  chain->SetBranchAddress("Jets_HTMask",&Jets_HTMask);
  chain->SetBranchAddress("Jets_ID",&Jets_ID);
  chain->SetBranchAddress("Jets_ISRMask",&Jets_ISRMask);
  chain->SetBranchAddress("Jets_jecFactor",&Jets_jecFactor);
  chain->SetBranchAddress("Jets_jecUnc",&Jets_jecUnc);
  chain->SetBranchAddress("Jets_jerFactor",&Jets_jerFactor);
  chain->SetBranchAddress("Jets_jerFactorDown",&Jets_jerFactorDown);
  chain->SetBranchAddress("Jets_jerFactorUp",&Jets_jerFactorUp);
  chain->SetBranchAddress("Jets_LeptonMask",&Jets_LeptonMask);
  chain->SetBranchAddress("Jets_MHTMask",&Jets_MHTMask);
  chain->SetBranchAddress("Jets_muonEnergyFraction",&Jets_muonEnergyFraction);
  chain->SetBranchAddress("Jets_muonMultiplicity",&Jets_muonMultiplicity);
  chain->SetBranchAddress("Jets_neutralEmEnergyFraction",&Jets_neutralEmEnergyFraction);
  chain->SetBranchAddress("Jets_neutralHadronEnergyFraction",&Jets_neutralHadronEnergyFraction);
  chain->SetBranchAddress("Jets_neutralHadronMultiplicity",&Jets_neutralHadronMultiplicity);
  chain->SetBranchAddress("Jets_neutralMultiplicity",&Jets_neutralMultiplicity);
  chain->SetBranchAddress("Jets_partonFlavor",&Jets_partonFlavor);
  chain->SetBranchAddress("Jets_photonEnergyFraction",&Jets_photonEnergyFraction);
  chain->SetBranchAddress("Jets_photonMultiplicity",&Jets_photonMultiplicity);
  chain->SetBranchAddress("Jets_qgAxis2",&Jets_qgAxis2);
  chain->SetBranchAddress("Jets_qgLikelihood",&Jets_qgLikelihood);
  chain->SetBranchAddress("Jets_qgMult",&Jets_qgMult);
  chain->SetBranchAddress("Jets_qgPtD",&Jets_qgPtD);
  chain->SetBranchAddress("JetsAK8",&JetsAK8);
  chain->SetBranchAddress("JetsAK8_bDiscriminatorSubjet1CSV",&JetsAK8_bDiscriminatorSubjet1CSV);
  chain->SetBranchAddress("JetsAK8_bDiscriminatorSubjet2CSV",&JetsAK8_bDiscriminatorSubjet2CSV);
  chain->SetBranchAddress("JetsAK8_doubleBDiscriminator",&JetsAK8_doubleBDiscriminator);
  chain->SetBranchAddress("JetsAK8_ID",&JetsAK8_ID);
  chain->SetBranchAddress("JetsAK8_NsubjettinessTau1",&JetsAK8_NsubjettinessTau1);
  chain->SetBranchAddress("JetsAK8_NsubjettinessTau2",&JetsAK8_NsubjettinessTau2);
  chain->SetBranchAddress("JetsAK8_NsubjettinessTau3",&JetsAK8_NsubjettinessTau3);
  chain->SetBranchAddress("JetsAK8_NumBhadrons",&JetsAK8_NumBhadrons);
  chain->SetBranchAddress("JetsAK8_NumChadrons",&JetsAK8_NumChadrons);
  chain->SetBranchAddress("JetsAK8_prunedMass",&JetsAK8_prunedMass);
  chain->SetBranchAddress("madHT",&madHT);
  chain->SetBranchAddress("madMinDeltaRStatus",&madMinDeltaRStatus);
  chain->SetBranchAddress("madMinPhotonDeltaR",&madMinPhotonDeltaR);
  chain->SetBranchAddress("MET",&MET);
  chain->SetBranchAddress("METDown",&METDown);
  chain->SetBranchAddress("METPhi",&METPhi);
  chain->SetBranchAddress("METPhiDown",&METPhiDown);
  chain->SetBranchAddress("METPhiUp",&METPhiUp);
  chain->SetBranchAddress("METUp",&METUp);
  chain->SetBranchAddress("MHT",&MHT);
  chain->SetBranchAddress("MHTPhi",&MHTPhi);
  chain->SetBranchAddress("MT2",&MT2);
  chain->SetBranchAddress("Muons",&Muons);
  chain->SetBranchAddress("Muons_charge",&Muons_charge);
  chain->SetBranchAddress("Muons_MT2Activity",&Muons_MT2Activity);
  chain->SetBranchAddress("Muons_MTW",&Muons_MTW);
  chain->SetBranchAddress("Muons_PTW",&Muons_PTW);
  chain->SetBranchAddress("Muons_tightID",&Muons_tightID);
  chain->SetBranchAddress("MuonsNoIso",&MuonsNoIso);
  chain->SetBranchAddress("MuonsNoIso_MiniIso",&MuonsNoIso_MiniIso);
  chain->SetBranchAddress("MuonsNoIso_MT2Activity",&MuonsNoIso_MT2Activity);
  chain->SetBranchAddress("MuonsNoIso_MTW",&MuonsNoIso_MTW);
  chain->SetBranchAddress("MuonsNoIso_tightID",&MuonsNoIso_tightID);
  chain->SetBranchAddress("nAllVertices",&nAllVertices);
  chain->SetBranchAddress("NJets",&NJets);
  chain->SetBranchAddress("NJetsISR",&NJetsISR);
  chain->SetBranchAddress("NumEvents",&NumEvents);
  chain->SetBranchAddress("NumInteractions",&NumInteractions);
  chain->SetBranchAddress("NVtx",&NVtx);
  chain->SetBranchAddress("PDFids",&PDFids);
  chain->SetBranchAddress("PDFweights",&PDFweights);
  chain->SetBranchAddress("PFCaloMETRatio",&PFCaloMETRatio);
  chain->SetBranchAddress("Photons",&Photons);
  chain->SetBranchAddress("Photons_electronFakes",&Photons_electronFakes);
  chain->SetBranchAddress("Photons_fullID",&Photons_fullID);
  chain->SetBranchAddress("Photons_genMatched",&Photons_genMatched);
  chain->SetBranchAddress("Photons_hadTowOverEM",&Photons_hadTowOverEM);
  chain->SetBranchAddress("Photons_hasPixelSeed",&Photons_hasPixelSeed);
  chain->SetBranchAddress("Photons_isEB",&Photons_isEB);
  chain->SetBranchAddress("Photons_nonPrompt",&Photons_nonPrompt);
  chain->SetBranchAddress("Photons_passElectronVeto",&Photons_passElectronVeto);
  chain->SetBranchAddress("Photons_pfChargedIso",&Photons_pfChargedIso);
  chain->SetBranchAddress("Photons_pfChargedIsoRhoCorr",&Photons_pfChargedIsoRhoCorr);
  chain->SetBranchAddress("Photons_pfGammaIso",&Photons_pfGammaIso);
  chain->SetBranchAddress("Photons_pfGammaIsoRhoCorr",&Photons_pfGammaIsoRhoCorr);
  chain->SetBranchAddress("Photons_pfNeutralIso",&Photons_pfNeutralIso);
  chain->SetBranchAddress("Photons_pfNeutralIsoRhoCorr",&Photons_pfNeutralIsoRhoCorr);
  chain->SetBranchAddress("Photons_sigmaIetaIeta",&Photons_sigmaIetaIeta);
  chain->SetBranchAddress("PmssmId",&PmssmId);
  chain->SetBranchAddress("puSysDown",&puSysDown);
  chain->SetBranchAddress("puSysUp",&puSysUp);
  chain->SetBranchAddress("puWeight",&puWeight);
  chain->SetBranchAddress("ScaleWeights",&ScaleWeights);
  chain->SetBranchAddress("SoftJets",&SoftJets);
  chain->SetBranchAddress("SoftJets_bDiscriminatorCSV",&SoftJets_bDiscriminatorCSV);
  chain->SetBranchAddress("SoftJets_ID",&SoftJets_ID);
  chain->SetBranchAddress("SoftJets_jecFactor",&SoftJets_jecFactor);
  chain->SetBranchAddress("SoftJets_jecUnc",&SoftJets_jecUnc);
  chain->SetBranchAddress("SoftJets_jerFactor",&SoftJets_jerFactor);
  chain->SetBranchAddress("SoftJets_jerFactorDown",&SoftJets_jerFactorDown);
  chain->SetBranchAddress("SoftJets_jerFactorUp",&SoftJets_jerFactorUp);
  chain->SetBranchAddress("SusyLSPMass",&SusyLSPMass);
  chain->SetBranchAddress("SusyMotherMass",&SusyMotherMass);
  chain->SetBranchAddress("TAPElectronTracks",&TAPElectronTracks);
  chain->SetBranchAddress("TAPElectronTracks_activity",&TAPElectronTracks_activity);
  chain->SetBranchAddress("TAPElectronTracks_charge",&TAPElectronTracks_charge);
  chain->SetBranchAddress("TAPElectronTracks_mT",&TAPElectronTracks_mT);
  chain->SetBranchAddress("TAPElectronTracks_trkiso",&TAPElectronTracks_trkiso);
  chain->SetBranchAddress("TAPMuonTracks",&TAPMuonTracks);
  chain->SetBranchAddress("TAPMuonTracks_activity",&TAPMuonTracks_activity);
  chain->SetBranchAddress("TAPMuonTracks_charge",&TAPMuonTracks_charge);
  chain->SetBranchAddress("TAPMuonTracks_mT",&TAPMuonTracks_mT);
  chain->SetBranchAddress("TAPMuonTracks_trkiso",&TAPMuonTracks_trkiso);
  chain->SetBranchAddress("TAPPionTracks",&TAPPionTracks);
  chain->SetBranchAddress("TAPPionTracks_activity",&TAPPionTracks_activity);
  chain->SetBranchAddress("TAPPionTracks_charge",&TAPPionTracks_charge);
  chain->SetBranchAddress("TAPPionTracks_mT",&TAPPionTracks_mT);
  chain->SetBranchAddress("TAPPionTracks_trkiso",&TAPPionTracks_trkiso);
  chain->SetBranchAddress("TriggerNames",&TriggerNames);
  chain->SetBranchAddress("TriggerPass",&TriggerPass);
  chain->SetBranchAddress("TriggerPrescales",&TriggerPrescales);
  chain->SetBranchAddress("TrueNumInteractions",&TrueNumInteractions);
  chain->SetBranchAddress("Weight",&Weight);
  chain->SetBranchAddress("ZCandidates",&ZCandidates);
  chain->SetBranchAddress("HT5",&HT5);
  chain->SetBranchAddress("RA2bin",&RA2binBranch);
  chain->SetBranchAddress("RA2bins",&RA2bins);
  };
